version: '3.9'

services:
  db:
    image: postgres:16   # Especificando a versão 16 do PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: galeria
    ports:
      - '5432:5432'
    volumes:
      - /data:/var/lib/postgresql/data
    networks:
      - galeria_network   # Adicionando uma rede para garantir comunicação adequada

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - '15432:80'
    depends_on:
      - db
    networks:
      - galeria_network   # Garantindo que o PgAdmin esteja na mesma rede do banco de dados

networks:
  galeria_network:
    driver: bridge
